import type { Metadata } from "next";
import { DM_Sans,Inter, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({subsets : ['latin']})
const dmSans = DM_Sans({subsets : ['latin']})
export const metadata: Metadata = {
  title: "Bahtraku",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={dmSans.className}
      >
        {children}
      </body>
    </html>
  );
}
